os:
 - linux
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6.1"
  - "3.6.2"
  - "3.6.3"
  - "3.7-dev"
  - "pypy3"

before_install:
  - pip install pytest-cov
  - pip install codecov
  - pip install -r requirements.txt

install: python setup.py install
script: python setup.py test

after_success:
  - codecov
